### ISSUE TITLE
Text type fields saving as 255 limit

### ISSUE THREAD

**Issue by nickaccent** [accent-starlette/starlette-audit#3]
Table has a text type field,when audited is added the field fails to save as implements a 255 char limit.

**Comment by stuartaccent** [comment]
as discussed was the use of entity name coming frm the original model that was longer than 255 chars not the data itself. have limited the name to 255 chars here for safety

https://github.com/accent-starlette/starlette-audit/commit/f0449cd1b346e056505eb019de0313b36a6842fd
